### ISSUE TITLE
AUR Package

### ISSUE THREAD

**Issue by jonas-w** [nadrad/h-m-m#12]
Just wanted to inform you, that i created an AUR package for arch linux.
https://aur.archlinux.org/packages/h-m-m-git

This makes it easier for me to keep h-m-m up to date (And for others if they are interested)

I hope this was okay!

**Comment by nadrad** [comment]
Great, thanks! I thought about doing it myself, but it seemed too complicated. I just added a note about it to the readme file. 

The package shows xclip and similar applications as *optional*. h-m-m doesn't really work without them. Should it become mandatory, or it's just the way it works?

For php, should we also add mbstring if the php version is below 8, or can we simply assume that it's always the latest version in Arch? :)

**Comment by jonas-w** [comment]
@nadrad yes you're right, i just made it optdepends as i didn't want it to install all these different clipboard implementations if only one is needed. 

I will look at it again and try to find a solution!

The "php" package is always the latest. The other versions are called php7/php53 etc.

**Comment by nadrad** [comment]
I see. So, maybe something like "if it's wayland, then wl-clipboard is required, and otherwise, if there's no xsel, then xclip is required".

**Comment by jonas-w** [comment]
exactly. I looked at some other packages that require xclip or wl-clipboard and they all seem to do this as an optdepend.

Maybe there isn't a good solution that isn't too "hacky". But i will look further into it, as I'm really interested if this could be solved better.

Because you are right if someone simply installs it, without further inspecting the optdepends, there will be no clipboard application automatically installed.

**Comment by nadrad** [comment]
Thanks. I think it's good enough for now, but it would be great if you could find a way one day to refine the dependency.

**Comment by jonas-w** [comment]
https://bbs.archlinux.org/viewtopic.php?pid=2057656

seems like it is the only way...

**Comment by nadrad** [comment]
I expected more from AUR ;)  Thanks for checking.
