### ISSUE TITLE
Drawing bug when using it on macOS

### ISSUE THREAD

**Issue by diegomichel** [nadrad/h-m-m#13]
Hi,

This bug is present on MacOS, when using kitty with tmux, standalone kitty, or terminal app.

<img width="911" alt="Screen Shot 2022-09-15 at 10 10 42" src="https://user-images.githubusercontent.com/848433/190454139-39266600-cbb6-4640-8923-b60bae5f6944.png">

```
~/github/h-m-m (main ✗) php -v
PHP 8.1.10 (cli) (built: Sep  4 2022 08:41:25) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.10, Copyright (c) Zend Technologies
    with Zend OPcache v8.1.10, Copyright (c), by Zend Technologies
```

shortcuts file content:
```
root
	Adding, editing or removing nodes
		o create new sibling
		O create new child
		y yanks active and descendants
		Y yanks descendants
		d deletes active node and descendants
		D deletes descendants
		p paste as descendants
		P paste as siblings
		ctrl-p appends the clipboard at the end of the active node title
		e edit current node
		E edits current node replacing content
	Relative navigating/moving
		h or left go back to parent
		l or right go to the middle child
		k or up upper sibling
		j or down lower sibling
		J move down
		K move up

```

I tried changing fonts to see if that was the issue, but the issue remains. Let me know if you want me to try different settings or terminal apps to figure this out; thanks!.

**Comment by nadrad** [comment]
I think that was the remaining BOM bytes from the multi byte characters that have remained in your file. (when you replaced the down arrow symbol with the word 'down', the symbol was removed but not the BOM bytes). It makes it think the line is longer than it really is. 

Now the code removes all the BOM bytes. I think it should solve this and similar problems.
