### ISSUE TITLE
Pasting as a descendants doesn't work anymore

### ISSUE THREAD

**Issue by jonas-w** [nadrad/h-m-m#22]
As the title says. When descendants where cut and pasted it doesn't paste them as descendants anymore but as a text on a new descending node.

EDIT: seems to have something to do with these two commits:
13b5f6c165c1be7d41cc0b66dc9192209d4ed6bc
f65979bbd047cee71fe00259993dd7abed5dd63f

**Comment by nadrad** [comment]
Oh... I completely forgot about \t and \n where it cleans the control characters! It's fine now.

**Comment by jonas-w** [comment]
Thanks, seems to work!
