### ISSUE TITLE
Add undo feature

### ISSUE THREAD

**Issue by klammbueddel** [nadrad/h-m-m#3]
Hi Nader,

nice tool, love it. Could you please add undo (u) / redo (Ctrl + r) feature.

That would be pretty neat ;)

Keep up the good work!

**Comment by nadrad** [comment]
I'm glad you like it. 

Yes, it's in my todo list, although, toward the bottom of the list for now :)
One thing that helps until having undo is the fact that when you delete something, it goes to the clipboard. So if it was a mistake, you can simply paste it. This is, of course, limited to one mistake in a row!

**Comment by klammbueddel** [comment]
Yes, some kind of autosave would help, too, if synced to some cloud storage this provides a feasible version history in case of an accident.

**Comment by nadrad** [comment]
Oh, I don't feel comfortable about auto save in general!
I'll add the undo feature... don't worry :)

**Comment by klammbueddel** [comment]
Nice to see the ongoing discussion on hacker news ;) Thank you for cranking out this feature that fast.

**Comment by nadrad** [comment]
Actually, someone else contributed the code :)  That's when you really enjoy open source!
