### ISSUE TITLE
Config location

### ISSUE THREAD

**Issue by jonas-w** [nadrad/h-m-m#30]
I think it would be better to put the config in XDG_CONFIG_HOME ($HOME/.config/). I don't know the locations for other Operating Systems.

If the script is in e.g. /usr/bin the user would need root rights to edit the config and there would not be an option for per user configuration on multi user systems.
Also having configs in /usr/bin is not good/common practice.

**Comment by nadrad** [comment]
Yes, it's not fine now. I was also thinking about having more options for settings: 

command line arguments > environmental variables > config file > defaults 

There can be one extra command line argument to introduce a config file in a non-default location as well. Although, I'm thinking whether or not it's required to have a config file when people can simply use environment variables. I guess it's easier for most people to use a config file.

**Comment by nadrad** [comment]
Done. There's more information about it in the readme file.
