### ISSUE TITLE
Ctrl+Backspace doesn't work properly and can crash the program

### ISSUE THREAD

**Issue by gregopet** [nadrad/h-m-m#35]
When I am editing the contents of a node, I can Ctrl+Backspace until I come to the last word.

- when I want to delete the last word, its first letter remains in the prompt
- if I press Ctrl+Backspace once more, the program crashes
- if I delete that letter instead, and press Ctrl+Backspace in the emptied prompt, it also crashes
- even if I start a completely new node and just Ctrl+Backspace before entering any text, it crashes

... this is also how I learned there is no autosave (yet) :sweat_smile:

**Comment by nadrad** [comment]
It's fixed now.

p.s. autosave is evil ;)
