### ISSUE TITLE
Cannot paste when ssh into a headless server

### ISSUE THREAD

**Issue by chunjiw** [nadrad/h-m-m#38]
Thank you for this awesome project!

I noticed #11 and #15 but they both involve docker. I set h-m-m up twice, one in a x64 Debian, the other in a raspberry pi. I cannot paste in any of them. The error says `Error: Can't open display: (null)`. I think the reason is that both servers have no display.

**Comment by nadrad** [comment]
[a61e4ac](https://github.com/nadrad/h-m-m/commit/a61e4acfc7ff753592f9ce8e6686a0cff4547f78) may help. Otherwise, I'm not sure if there's anything else possible. But let me know if you could think of anything else :)
