### ISSUE TITLE
Feature Request: Auto Delete Empty Nodes

### ISSUE THREAD

**Issue by Countryen** [nadrad/h-m-m#40]
Could you please add that empty nodes are deleted automatically when finishing the node with enter/esc?
If empty nodes serve any purpose, of course, add an option for it.

What I currently do:
- Press enter (new node spawns)
- Enter text
- Press enter (node is finished with some text)
- Press enter again <- to start a new node
- Remember, that I'd rather do something else
- Press enter/esc to close the node
- **Press d to delete the node**

What I'd like to do:
- Press enter (new node spawns)
- Enter text
- Press enter (node is finished with some text)
- Press enter again <- to start a new node
- Remember, that I'd rather do something else
- Press enter/esc to close the node
- **The node is gone because empty and I don't have to delete it manually**

Of course, that's just press step less, but can be very annoying for quick brain storming to always remember.

I hope this explains what I mean, feel free to ask if not.

**Comment by nadrad** [comment]
Makes sense.
Done.
