### ISSUE TITLE
Line misalignment

### ISSUE THREAD

**Issue by sofomryu** [nadrad/h-m-m#41]
![h-m-m_misalignment](https://user-images.githubusercontent.com/69798848/200225409-efea0f60-4e97-40c0-8d95-f32b00abfb38.png)

Hi! I am enjoying using h-m-m.
I have an misalignment issue when merging a node to the other node.
As you can see from the screenshot, line between third node and fourth node, fourth node and fifth node, fifth node and sixth node doesn't align well.

How to fix this?

**Comment by llagerlof** [comment]
@sofomryu I am not the developer, but if you can share the problematic .hmm file will be easier to find the issue. Or at least provide the steps to reproduce the problem.

**Comment by nadrad** [comment]
Yes, I'm aware of it :)  It happens when there's only one node in each level and they have different heights. 
I'll get to it one day, but it doesn't have a high priority because I never have that situation in real life (each node normally has multiple children in my maps).

**Comment by nadrad** [comment]
I think 5e216d6dad81b45556d5a070cced18d5826ddc8b has solved it.
