### ISSUE TITLE
mb_internal_encoding("UTF-8");

### ISSUE THREAD

**Issue by Kola13** [nadrad/h-m-m#44]
Get this error:

PHP Fatal error:  Uncaught Error: Call to undefined function mb_internal_encoding() in /usr/local/bin/h-m-m:17
Stack trace:
#0 {main}
  thrown in /usr/local/bin/h-m-m on line 17

I'm a newb, but I think it has to do with defining PHP to work with line 17, but I'm not too sure why.

mb_internal_encoding("UTF-8");

Thanks

**Comment by nadrad** [comment]
You're using an old version of php. Install `mbstring` to solve the problem; e.g., `sudo apt install php7.2-mbstring` in Ubutu (replace 7.2 with the actual php version if it's different).
