### ISSUE TITLE
Grandchild vertical alignment

### ISSUE THREAD

**Issue by Svalorzen** [nadrad/h-m-m#48]
Great project!

I was wondering if there was a way to force the grandchildren of a particular node to be aligned. In other words, given the following picture, I'd love for the A node and B node to have the same `x` coordinate, rather than be offset by the length of their parents:

![image](https://user-images.githubusercontent.com/1609228/224503451-d2ed8650-e688-4865-8cbe-f70661cb79f9.png)

**Comment by nadrad** [comment]
That's actually how it used to be at the beginning, but then I worked a lot more on it to turn it into what you see right now! The advantage for the current form instead of one where items of the same level have the same x coordinate is that different branches are visually distinguishable like this.

What's your reason for preferring the other way, aesthetics or function?

**Comment by Svalorzen** [comment]
It does generally make a lot more sense, and I agree. In my case I have:

- Grandparent is a group
- Children are simple short names
- Each child has a single grandchild, which contains some long descriptive text.

Essentially, each child and grandchild is in practice a single "element", it's just that I'm using the children to make the short names stand out, and the grandchildren to contain the descriptive text. In just this particular case, it'd be cool to have the various grandchildren descriptive text be aligned for aesthetics.

Example from my diagram:

![image](https://user-images.githubusercontent.com/1609228/224510615-45aedcc0-a2d0-4949-b2f2-0285c6aa8c3b.png)

It would be awesome to store this preference per-node, although I have noticed that because your save file format is a simple text container, so maybe saving format information for specific nodes in particular is something you are not keen to do.

A global switch would still be cool to see how it looks I guess, although if you say that you tried it and it was not great I believe you :)

**Comment by Svalorzen** [comment]
Or maybe you could detect if all children have at most a single child? Could still be really helpful.

**Comment by Svalorzen** [comment]
Or (and after this I'll stop writing I swear), maybe there could be a threshold below which grandchildren are aligned? Like, if they are offset at most X, then align, otherwise keep their current location. Could sweep from shortest to longest to avoid a combinatorial search.

**Comment by Svalorzen** [comment]
Because I do not like to ask for features without putting in at least some work, I have made a smallish change that somewhat "normalizes" the x positions of the nodes a little bit, avoiding "off by 1" nodes.

Note that I am by no means a PHP expert, so it might look a bit ugly:

```php

     \\ In calculate_x_and_lh, line 549, after the first x computation
     $found = false;
     foreach ( $mm['xsnap'] as $v ) {
         if (abs($v - $mm['nodes'][$id]['x']) <= $mm['xsnap_dist']) {
             $mm['nodes'][$id]['x'] = $v;
             $found = true;
         }
 
         if ( $v >= $mm['nodes'][$id]['x'] )
             break;
     }
     if (!$found) {
         array_push($mm['xsnap'], $mm['nodes'][$id]['x']);
         sort($mm['xsnap']);
     }
 
     \\ In build_map
     $mm['xsnap_dist'] = 4;
     $mm['xsnap'] = [];
```

So the idea is that you keep a list of previously computed `x`es, and you try to match the new node to the closest one, as long as it is within a certain threshold (in this case 4, kept in `xsnap_dist`). It's probably not super smart, and the output also slightly depends on the order in which the nodes are processed (since that determines the values of the numbers that get cached).

However, the output doesn't look too bad I think!

Before:
![image](https://user-images.githubusercontent.com/1609228/224514974-14efe099-5e7e-4d11-8424-9691de2c1c3a.png)

After:
![image](https://user-images.githubusercontent.com/1609228/224514986-b12ea7b3-233e-435e-ae04-92e467c04569.png)

**Comment by Svalorzen** [comment]
This also seems to mess a bit with the drawing of the connections; I admit I haven't looked into it too much yet :P

**Comment by nadrad** [comment]
I see what you have in mind. I've also had a couple of cases when such a view could be helpful (e.g., when we were thinking about selecting a name and listed all the abbreviations, each with a single child that showed what it stood for).

I've added the new view. You can toggle between the two views using `|`, and change the default with `align_levels`.
