### ISSUE TITLE
Current node is not highlighted in certain circumstances

### ISSUE THREAD

**Issue by infinitewhileloop** [nadrad/h-m-m#53]
Thanks a lot for creating this very useful tool. 

I noticed a minor issue. When enabling aligned levels using the `|` key, active nodes without siblings aren't highlighted. E.g. in the screenshot, the node `golf` is activated (the text editor shows this), but the node isn't highlighted.

![image](https://user-images.githubusercontent.com/84473512/232897081-353729a8-9ffa-4afd-b8ea-70a9dcf22315.png)

**Comment by akashpal-21** [comment]
I can confirm this bug, this happens when aligned levels is true and the node has only one entry. Highlight returns when second sibling is added.

Idk how to fix, but a fix would greatly improve working with large and messy maps.

**Comment by nadrad** [comment]
Fixed :)

**Comment by akashpal-21** [comment]
Much thanks :)

**Comment by infinitewhileloop** [comment]
Thanks a lot. I have updated the application and the issue has now indeed disappeared.
