### ISSUE TITLE
Auto Save functionality

### ISSUE THREAD

**Issue by samuellawerentz** [nadrad/h-m-m#55]
This tool is awesome. Thank you!

Sometimes, I forget to save and close the terminal or my system shuts down. It would be awesome to provide autosave feature. Thanks.

**Comment by nadrad** [comment]
I don't like auto save :')   

However, it's not difficult to implement, and it can be an option that is off by default, and people who like it can enable it. I'll add it soon.

**Comment by nadrad** [comment]
Now there's an `auto_save` setting. The default value is "false", and you can change it if you want.
