### ISSUE TITLE
Feature request: make key bindings more Vim-like or allow users to remap key bindings

### ISSUE THREAD

**Issue by infinitewhileloop** [nadrad/h-m-m#57]
Thank you for developing this wonderful application.
Sometimes I have a hard time remembering the key bindings, so it would be helpful to make them more Vim-like, or to allow the user to remap the default key bindings.

Here are some ideas how I would remap the default key bindings (a couple are conflicting with current key bindings):
* `e`, `i`, or `a` - edits the active node -> add `I` and `A`, where `I` puts the cursor in front of the first character, `A` puts the cursor after the last character
* `E`, `I`, or `A` - edits the active node, ignoring the existing text -> use `cw` or `cc` instead
* `c` - centers the active node on the screen -> use `zz` instead
* `v` - collapses everything other than the first-level nodes -> use `zM` instead (similar to folding in Vim)
* `V` - collapses all the children of the active node -> use `zC` instead
* `b` - expands all nodes -> use `zR` instead
* `s` - saves with the previous file name (or asks for one if there's none) -> use `w` instead
* `ctrl+h` - hides/views hidden nodes -> I already remapped `ctrl+h` in Tmux to switch Tmux windows, so I can't use this feature at the moment
* `ctrl+u` in the text editor to remove everything in front of the cursor

**Comment by nadrad** [comment]
Yeah... I'll add configuration. Although, it only accepts single key bindings now. I have to add key sequence binding as well anyway, because I'm running out of single keys for new features.

**Comment by nadrad** [comment]
OK, with the last two commits, it's become possible to configure key bindings, and you can also press '?' to see the current key bindings.

**Comment by infinitewhileloop** [comment]
Thanks a lot for adding this feature. 

Just a small heads-up: `bind end = save` and `bind home = save` isn't working on my system, even though it's showing up when I press the `?` key. Binding other keys works without issues.

**Comment by nadrad** [comment]
Pull the latest version, and with that, change the keys to `home_alternative` and `end_alternative` and see whether or not it works (and let me know).

If it didn't work, run `h-m-m --echo-keys`, press the "home" and "end" keys, see which code is shown on the top-left corner of the screen, and let me know.

**Comment by infinitewhileloop** [comment]
Adding `_alternative` doesn't solve this issue for my system.
Pressing the `Home` key shows `33 133 61 176`, pressing `End` displays `33 133 64 176`.
I wasn't really planning on remapping these keys anyway, I just noticed this while experimenting a bit.

**Comment by nadrad** [comment]
I don't know why your key codes for "home" and "end" keys are different from mine! Regardless, I've set the `home_alternative` and `end_alternative` values to those, in case someone needs them.
