### ISSUE TITLE
Adding a background to inactive nodes

### ISSUE THREAD

**Issue by Thorinori** [nadrad/h-m-m#58]
Hey, I am not super familiar with php particularly so I am having a bit of difficulty figuring out how to integrate this myself at the moment, but I believe there should be a config option for changing the inactive nodes coloration, just like with the active node. Or if there is a way already I may have just missed it apparently, and some help would be appreciated, thanks! Love using this though, it has definitely helped me keep some stuff organized.

**Comment by nadrad** [comment]
The foreground and background colors for inactive nodes are your terminal's default colors, and you can change them within your terminal settings.

If you're thinking about having a background for inactive nodes different from the overall background, I'm afraid that's a difficult thing to do with the way I've written the program! I've planned to rewrite it in the future with a more general perspective that can allow flexibilities such as these, but it can't be feasibly done with this version.

**Comment by Thorinori** [comment]
Ah that makes sense, thanks! Hope the rewrite goes well! If I may make a suggestion, unless it isn't really feasible for some reason, maybe move to a hexcode color system or something, or at least enable it to be a possibility? Ascii codes can be kind of annoying at least to me, but they do seem like an interesting way to do things too.
