### ISSUE TITLE
Change file extension to md

### ISSUE THREAD

**Issue by Phantasimay** [nadrad/h-m-m#59]
hi nadrad, your project are awsome. i just want to purpose to change your extension file to md. so it will more compatible with markdown and pandoc. i think it will amazing to have mind map on universal note syntax (markdown)

**Comment by nadrad** [comment]
I'm glad you like it.

Are you looking for something like the following?

`sed 's|^\(\t*\)\(.\+\)|\1* \2|' example.hmm | pandoc -f markdown -o example.html`

**Comment by Phantasimay** [comment]
> I'm glad you like it.
> 
> Are you looking for something like the following?
> 
> `sed 's|^\(\t*\)\(.\+\)|\1* \2|' example.hmm | pandoc -f markdown -o example.html`

It is cool. But what I mean is. We can integrate your project with note taking system flawlessly if you use markdown extension. So on every node I can use `[example](./link/dir/other/note/)` to link it with my other note. It will more cool if it can open note under cusor in editor(nvim) if I press enter.

**Comment by nadrad** [comment]
You can have a node like "./link/dir/other/note.txt", and when you press ctrl+o when it's active: it opens it with your default application via xdg-open. It can be used for local files, Web URLs, etc.

The point is that most of the markdown features are not applicable to this type of content (e.g., headings, lists, images, and code blocks). A few of them that may be applicable can be satisfied in other, simpler ways. So, if you have other needs that a potential markdown file can satisfy, let me know and we can see how it's possible to do them with the current format of h-m-m.
