### ISSUE TITLE
PHP warning on calling script -> line 397

### ISSUE THREAD

**Issue by akashpal-21** [nadrad/h-m-m#60]
The following errors are outputted on terminal when calling the script. 

`PHP Warning:  Undefined array key "config" on line 397`
`PHP Warning:  foreach() argument must be of type array|object, null given on line 397`

Line 397 in question: 

`397   foreach ($mm['config'] as $key=>$value)`

**Comment by llagerlof** [comment]
@akashpal-21 Let me guess. PHP 8.x ?

**Comment by akashpal-21** [comment]
@llagerlof yes,, but doesnt affect any usage. Just spam on the terminal.

**Comment by klozamarek** [comment]
same here

**Comment by nadrad** [comment]
I've made a small change that may fix it. Let me know if the latest version works for you.

**Comment by nadrad** [comment]
I'm glad to hear that :)
