### ISSUE TITLE
`h-m-m` Permission denied in Docker

### ISSUE THREAD

**Issue by vimalk78** [nadrad/h-m-m#64]
```
$ docker build -t hmm .
...
...
STEP 5/6: COPY ./h-m-m .
--> 9b46e4f6a713
STEP 6/6: CMD ["./h-m-m"]
COMMIT hmm
--> eeb8910cbf86
Successfully tagged localhost/hmm:latest

$ docker run --rm -it -v $(pwd):/app/ hmm:latest
/usr/local/bin/docker-php-entrypoint: 9: exec: ./h-m-m: Permission denied
```

**Comment by nadrad** [comment]
I have no idea how Docker works. Maybe @vc0sta can help.

**Comment by hashguide** [comment]
Do you have your non-root user added to the docker group? Also, h-m-m after install is owned by root:root. I have an additional group I created for root tools that I added myself to and changed the group owner of `/usr/local/bin/h-m-m`

**Comment by hashguide** [comment]
So, I figured out that  
1) Need to chmod u+x the script to make it executable 
2) The PHP container hasn't allowed me to mount a volume whether with `-v` or by using `--mount type=bind...` So if you want to save files, use the host version, not docker, unfortunately.  
Maybe one of the other php images would work, but I don't have time to look into that. I'll create a PR to add the additional line I added to make it work without saving on host machine.

**Comment by wschroeder** [comment]
Interestingly, this worked fine for me using Docker on MacOS as well as WSL/Kali in Windows. The executable bit was already set on `h-m-m` in the repository, so there was nothing new for Docker to do during the build. I wonder what the specific environment was that had this problem.

**Comment by hashguide** [comment]
I am using a debian based linux, ubuntu. I tried each and every way and the only way I was allowed was after making the file executable. The php image is built using various architectures, maybe that has something to do with it.

**Comment by hashguide** [comment]
What command did you use to launch the container?

**Comment by wschroeder** [comment]
vimalk78 (with failuer) and I (with success) used:

```
docker build -t hmm .
docker run --rm -it -v $(pwd):/app/ hmm:latest
```

**Comment by hashguide** [comment]
actually, I just remembered that I copied the raw script, not cloned the repo. I see now that its executable with the cloned repo. My bad.

**Comment by wschroeder** [comment]
If your PR includes something like

```
EXEC chmod +x h-m-m
```

I'm confident you fixed it for whatever situation vimalk78 ran into! 😄

**Comment by hashguide** [comment]
> If your PR includes something like
> 
> ```
> EXEC chmod +x h-m-m
> ```
> 
> I'm confident you fixed it for whatever situation vimalk78 ran into! 😄

If vimalk78 clones the repo, he won't need to make the file executable. If copies the it raw from github, he will. Should just leave it as is. Not sure why the volume mounting doesn't work, but I use it without docker anyways. 

@vimalk78 try using without volume or on host machine, sorry!

**Comment by hashguide** [comment]
@wschroeder @vimalk78  it seems to work perfectly for me when I clone the github repo 🤷

**Comment by nadrad** [comment]
So, is everything OK? Can we close the issue?

**Comment by nadrad** [comment]
I have no idea what's going on here, but it's been a long time and I assume anything positive that could happen has happened. I'm going to close it. Feel free to open it if there's still an issue.
