### ISSUE TITLE
Support wide character display and input method

### ISSUE THREAD

**Issue by jheroy** [nadrad/h-m-m#68]
<img width="383" alt="image" src="https://github.com/nadrad/h-m-m/assets/504766/48d1846b-ca4d-41d3-9636-c1ddf65652db">

As shown in the figure, the Chinese node is misaligned. Each time an input method is selected in the input box, a new line is generated.

**Comment by nadrad** [comment]
Thanks for fixing it yourself. I didn't know about the difference between mb_strwidth and mb_strlen!

There's something else that can be fixed for wide characters: When the active node doesn't have any children, its highlighted area is bigger than expected, and when it does have children, its children are further away from it than expected. Would you like to fix it yourself as well? :)

**Comment by jheroy** [comment]
> Thanks for fixing it yourself @jheroy . I didn't know about the difference between mb_strwidth and mb_strlen!
> 
> There's something else that can be fixed for wide characters: When the active node doesn't have any children, its highlighted area is bigger than expected, and when it does have children, its children are further away from it than expected. Would you like to fix it yourself as well? :)

I submitted a new pull request at #74.
