### ISSUE TITLE
Going right of terminal width results in messy output

### ISSUE THREAD

**Issue by wschroeder** [nadrad/h-m-m#71]
I was experimenting with a map larger than the width of my terminal (iTerm2 on MacOS):

<img width="1763" alt="image" src="https://github.com/nadrad/h-m-m/assets/796842/9c1d347d-8136-421e-963a-b2c1dc6c819b">

If I `c` center on "blue", I get this:

<img width="1764" alt="image" src="https://github.com/nadrad/h-m-m/assets/796842/11d0afb2-e6d5-414c-9c85-016522052b8f">

What I expect is this (I created this issue so I could PR my solution, so this screenshot comes from my solution):

<img width="1763" alt="image" src="https://github.com/nadrad/h-m-m/assets/796842/8f428b48-1d5d-489f-80d9-8787d0cb8f0c">

**Comment by hashguide** [comment]
Centering the nodes for does this as well. To get out of it, type `|`  
Not sure what the center node is supposed to do, but not really needed imo.

**Comment by wschroeder** [comment]
[Here](https://github.com/nadrad/h-m-m/pull/72) is the PR fix

**Comment by nadrad** [comment]
Thanks
