### ISSUE TITLE
Delete word with `ctrl + w` when editing text

### ISSUE THREAD

**Issue by bartkl** [nadrad/h-m-m#75]
When editing the text of a node, I'm used to delete words by pressing `ctrl + w`. It would be a great addition to be able to configure this with h-h-m, but as far as I can tell there's no way of doing this.

Thank you for this great program, it's just what I was looking for :)

**Comment by nadrad** [comment]
I'm glad you like it :)

The key bindings for the line editor are not configurable [yet].
I just added ctrl+w to the key bindings.
