### ISSUE TITLE
Support umlauts etc.

### ISSUE THREAD

**Issue by jonas-w** [nadrad/h-m-m#8]
For example the characters on my keyboard that i can't type on h-m-m would be: ä ö ü ß §
I have a german keyboard layout.

There are probably many more characters that are not supported from other languages.

**Comment by nadrad** [comment]
Yes, it can show non-ASCII characters in an existing file, save them, copy and paste them on the map, etc (assuming that the terminal emulator supports unicode). However, the editor doesn't recognize non-ASCII characters yet. I'll fix it.

**Comment by nadrad** [comment]
Done. 
It seems to be working fine, but give it a try and let me know, to be sure. 
Also, it may be limited to normal keys on the keyboard. Altgr and similar methods may not work.

**Comment by 0ofta** [comment]
I can confirm the change solving the problem for me.  I can now use æ ø å, in h-m-m.

**Comment by jonas-w** [comment]
Thanks even the altgr stuff works!
