### ISSUE TITLE
Non-docker installation on Ubuntu 24.04 cannot run with PHP 8

### ISSUE THREAD

**Issue by pbower** [nadrad/h-m-m#83]
Hi there,

Without running Docker, and following the installation instructions on ubuntu 24.04:

wget -q -O - 'https://raw.githubusercontent.com/nadrad/h-m-m/main/install.sh' | sh

Results in the following:

h-m-m
PHP Fatal error:  Uncaught Error: Call to undefined function mb_internal_encoding() in /usr/local/bin/h-m-m:18
Stack trace:
#0 {main}
  thrown in /usr/local/bin/h-m-m on line 18
  
  
Could this be fixed by any chance? Program looks great.

Thanks,
Pete

PHP 8.3.6 (cli) (built: Jun 13 2024 15:23:20) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.3.6, Copyright (c) Zend Technologies
    with Zend OPcache v8.3.6, Copyright (c), by Zend Technologies

**Comment by nadrad** [comment]
Sounds like you don't have `mbstring`, but I thought it's available in php 8+. If you run `php -m`, do you see "mbstring" in the list of modules? If you don't, installing "mbstring" in your package manager probably solves this problem.
