### ISSUE TITLE
AUR package is orphaned

### ISSUE THREAD

**Issue by hownioni** [nadrad/h-m-m#84]

**Comment by nadrad** [comment]
I just adopted it, but turned you need to learn how to maintain an AUR package :')  I'm busy with something now, and I can get to it in a few weeks. However, if anyone is willing to take it over, please do.

**Comment by nadrad** [comment]
Thanks for the explanation, @jonas-w. So, do I guess correctly that when someone installs it, it installs the latest version, but then won't update it for that person each time there's a new commit unless we manually change the version number in that file?

**Comment by nadrad** [comment]
I understand, @jonas-w. I think it's good enough for now then.
Ejoy your new distro, by the way ;)

**Comment by nadrad** [comment]
@jonas-w I thought it might be NixOS! I've been curious about it as well.
