### ISSUE TITLE
install goes fine but can't run

### ISSUE THREAD

**Issue by nkh** [nadrad/h-m-m#85]
PHP Fatal error:  Uncaught Error: Call to undefined function mb_internal_encoding() in /usr/local/bin/h-m-m:18
Stack trace:
#0 {main}
  thrown in /usr/local/bin/h-m-m on line 18

**Comment by nadrad** [comment]
You're using an old version of php. Install `mbstring` for the current version of php or switch to version 8 or newer.

**Comment by nkh** [comment]
PHP 8.1.12-1ubuntu4.3 (cli) (built: Aug 17 2023 17:37:48) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.12, Copyright (c) Zend Technologies
    with Zend OPcache v8.1.12-1ubuntu4.3, Copyright (c), by Zend Technologies


I'll install mbstring.

**Comment by mesartwell** [comment]
Confirming that, on my debian system, installing the `php-mbstring` package resolved the h-m-m install error.
